import 'problem.dart';

// ═══════════════════════════════════════════════════════════════════════════════════
// 📊 PROBLEM SUBMISSION MODEL - Problem-Based Learning
// ═══════════════════════════════════════════════════════════════════════════════════

/// Validation exception for problem submission
class ValidationException implements Exception {
  final String message;

  ValidationException(this.message);

  @override
  String toString() => message;
}

/// Submission constraints
class SubmissionConstraints {
  final String? budget;
  final String? timeline;
  final String? technical;
  final Map<String, dynamic> other;

  const SubmissionConstraints({
    this.budget,
    this.timeline,
    this.technical,
    this.other = const {},
  });

  factory SubmissionConstraints.fromJson(Map<String, dynamic> json) {
    return SubmissionConstraints(
      budget: json['budget'] as String?,
      timeline: json['timeline'] as String?,
      technical: json['technical'] as String?,
      other: Map<String, dynamic>.from(json['other'] as Map? ?? {}),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'budget': budget,
      'timeline': timeline,
      'technical': technical,
      'other': other,
    };
  }

  SubmissionConstraints copyWith({
    String? budget,
    String? timeline,
    String? technical,
    Map<String, dynamic>? other,
  }) {
    return SubmissionConstraints(
      budget: budget ?? this.budget,
      timeline: timeline ?? this.timeline,
      technical: technical ?? this.technical,
      other: other ?? this.other,
    );
  }
}

/// Problem submission form data
class ProblemSubmission {
  final String title;
  final String description;
  final String organization;
  final String organizationId;
  final ImpactArea impactArea;
  final String city;
  final List<String> requiredSkills;
  final int urgencyLevel;
  final DateTime? deadline;
  final List<String> attachments;
  final SubmissionConstraints constraints;

  ProblemSubmission({
    required this.title,
    required this.description,
    required this.organization,
    required this.organizationId,
    required this.impactArea,
    required this.city,
    this.requiredSkills = const [],
    this.urgencyLevel = 3,
    this.deadline,
    this.attachments = const [],
    this.constraints = const SubmissionConstraints(),
  }) {
    _validate();
  }

  /// Validate submission data
  void _validate() {
    // Title validation
    if (title.trim().isEmpty) {
      throw ValidationException('Başlık boş olamaz');
    }

    if (title.length > 200) {
      throw ValidationException('Başlık çok uzun (maksimum 200 karakter)');
    }

    // Description validation
    if (description.trim().isEmpty) {
      throw ValidationException('Açıklama boş olamaz');
    }

    if (description.length < 100) {
      throw ValidationException(
          'Açıklama çok kısa (minimum 100 karakter gerekli)');
    }

    if (description.length > 5000) {
      throw ValidationException('Açıklama çok uzun (maksimum 5000 karakter)');
    }

    // Organization validation
    if (organization.trim().isEmpty) {
      throw ValidationException('Organizasyon adı boş olamaz');
    }

    if (organizationId.trim().isEmpty) {
      throw ValidationException('Organizasyon ID boş olamaz');
    }

    // City validation
    if (city.trim().isEmpty) {
      throw ValidationException('Şehir seçilmelidir');
    }

    // Urgency level validation
    if (urgencyLevel < 1 || urgencyLevel > 5) {
      throw ValidationException('Aciliyet seviyesi 1-5 arasında olmalıdır');
    }

    // Deadline validation
    if (deadline != null && deadline!.isBefore(DateTime.now())) {
      throw ValidationException('Son tarih geçmişte olamaz');
    }

    // Attachments validation
    if (attachments.length > 3) {
      throw ValidationException('Maksimum 3 dosya eklenebilir');
    }
  }

  /// Convert to Problem model
  Problem toProblem({int impactScore = 50}) {
    return Problem(
      id: '', // Will be generated by service
      title: title,
      description: description,
      organization: organization,
      organizationId: organizationId,
      impactArea: impactArea,
      city: city,
      requiredSkills: requiredSkills,
      status: ProblemStatus.pending_review,
      urgencyLevel: urgencyLevel,
      impactScore: impactScore,
      submittedAt: DateTime.now(),
      deadline: deadline,
      attachments: attachments,
      constraints: constraints.toJson(),
    );
  }

  factory ProblemSubmission.fromJson(Map<String, dynamic> json) {
    return ProblemSubmission(
      title: json['title'] as String,
      description: json['description'] as String,
      organization: json['organization'] as String,
      organizationId: json['organizationId'] as String,
      impactArea: ImpactArea.values.firstWhere(
        (e) => e.name == json['impactArea'],
        orElse: () => ImpactArea.technology,
      ),
      city: json['city'] as String,
      requiredSkills: (json['requiredSkills'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          [],
      urgencyLevel: json['urgencyLevel'] as int? ?? 3,
      deadline: json['deadline'] != null
          ? DateTime.parse(json['deadline'] as String)
          : null,
      attachments: (json['attachments'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          [],
      constraints: json['constraints'] != null
          ? SubmissionConstraints.fromJson(
              json['constraints'] as Map<String, dynamic>)
          : const SubmissionConstraints(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'description': description,
      'organization': organization,
      'organizationId': organizationId,
      'impactArea': impactArea.name,
      'city': city,
      'requiredSkills': requiredSkills,
      'urgencyLevel': urgencyLevel,
      'deadline': deadline?.toIso8601String(),
      'attachments': attachments,
      'constraints': constraints.toJson(),
    };
  }

  ProblemSubmission copyWith({
    String? title,
    String? description,
    String? organization,
    String? organizationId,
    ImpactArea? impactArea,
    String? city,
    List<String>? requiredSkills,
    int? urgencyLevel,
    DateTime? deadline,
    List<String>? attachments,
    SubmissionConstraints? constraints,
  }) {
    return ProblemSubmission(
      title: title ?? this.title,
      description: description ?? this.description,
      organization: organization ?? this.organization,
      organizationId: organizationId ?? this.organizationId,
      impactArea: impactArea ?? this.impactArea,
      city: city ?? this.city,
      requiredSkills: requiredSkills ?? this.requiredSkills,
      urgencyLevel: urgencyLevel ?? this.urgencyLevel,
      deadline: deadline ?? this.deadline,
      attachments: attachments ?? this.attachments,
      constraints: constraints ?? this.constraints,
    );
  }
}

/// File attachment validation
class AttachmentValidator {
  static const int maxFileSizeBytes = 10 * 1024 * 1024; // 10MB
  static const List<String> allowedExtensions = [
    '.pdf',
    '.png',
    '.jpg',
    '.jpeg',
    '.csv',
    '.json',
  ];

  static void validateFile(String filePath, int fileSizeBytes) {
    // Check file size
    if (fileSizeBytes > maxFileSizeBytes) {
      throw ValidationException(
          'Dosya çok büyük (maksimum 10MB)');
    }

    // Check file extension
    final extension = filePath.toLowerCase().substring(
      filePath.lastIndexOf('.'),
    );

    if (!allowedExtensions.contains(extension)) {
      throw ValidationException(
          'Dosya tipi desteklenmiyor. İzin verilen: ${allowedExtensions.join(", ")}');
    }
  }

  static String getFileExtension(String filePath) {
    return filePath.toLowerCase().substring(filePath.lastIndexOf('.'));
  }

  static bool isImageFile(String filePath) {
    final extension = getFileExtension(filePath);
    return ['.png', '.jpg', '.jpeg'].contains(extension);
  }

  static bool isPdfFile(String filePath) {
    return getFileExtension(filePath) == '.pdf';
  }

  static bool isDataFile(String filePath) {
    final extension = getFileExtension(filePath);
    return ['.csv', '.json'].contains(extension);
  }
}
